### ISSUE TITLE
Set up your Kanban board

### ISSUE THREAD

**Issue by Maha-Magdy** [Maha-Magdy/egyptian-food-world#21]
Link to our GitHub project
https://github.com/Maha-Magdy/meals-world/projects/1

In the Meals World project, Mai and I will work on it.

**Comment by smcommits** [comment]
Hi @Maha-Magdy and @MaiRizk, 

You have done an excellent job. Your work appears to be fantastic. It displays great team efforts and fair distribution of work.
To meet the mandatory requirements, there is an issue that you still need to work on. You are almost there!

## Required Changes ♻️

- [x] **All cards with `group task` in the title should be assigned to someone (it does not matter to whom as you have the freedom with that).**

Following is a requirement from the [project description](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/setup_kanban_board.md)


_Each of the team members should assign themselves to the correct cards. **Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.**_

Your cards with the title `group tasks` have not been assigned to someone. Please fix this. 
![image](https://user-images.githubusercontent.com/59168430/133157495-b229bddd-8256-4655-9abf-978c1fe5620d.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by carlos-ssh** [comment]
Hi @Maha-Magdy  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
